### ISSUE TITLE
Issue with Installation on Python 3.11

### ISSUE THREAD

**Issue by fxd-gif** [glpcc/PokerPy#2]
Hey, I am encountering difficulties when trying to install the package with Python **3.11**. 

**Troubleshooting Steps Taken:**
1. Installed necessary build tools using `pip install build`.
2. Updated pip and setuptools.
3. Manually downloaded the src and attempted to install locally.

**Additional Information:**
- Operating System: win11
- Python Version: 3.11
- Pip Version:  23.3.2
- Setuptools Version: 69.0.3

Thank you!

**Comment by glpcc** [comment]
Hi, i've checked this and it seems to be a problem with an outdated version of pybind, i'm gonna commit the changes and if you can please tell me if the issue is resolved as soon as possible

**Comment by glpcc** [comment]
Fix implemented, you can try now

**Comment by fxd-gif** [comment]
It works!!! Thank you so much
